/*
 * @lc app=leetcode id=389 lang=cpp
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (52.85%)
 * Total Accepted:    139.4K
 * Total Submissions: 263.8K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
class Solution {
public:
    char findTheDifference(string s, string t) {
        int len=s.size();
        
        char ret=0xff;
        if(len>0)
        {
            ret=s[0];
            ret=ret^t[0];
        }
        for(int i=0;i<len;i++)
        {
            ret=ret^s[i];
            ret=ret^t[i];
        }
        return ret^t[t.size()-1];
    }
};

